# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e537c99d22e79d847c587f1f013fca5c7f94213ae4d35a65bfc0f4f411f373f8b49f9135a9ee84d40cea935f516c61b8d22d3292b4df80efbee1eb63b1cfb55c

test:
  secret_key_base: 2a796695692fddbfd8762241fe8ae02ca67fdaaccc4f657d77c68e203c3c40a8731fa2bb0d9c55b968d6a50457bfcfe6e291e7aacffb0b84d436a9f45a9e04bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
